metadata.format.version = "1.1"

[versions]

# Gradle plugins
blossom = "1.3.1"
shadowJar = "8.1.1"

[libraries]

[bundles]

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
